### ISSUE TITLE
Trasnform failed when running pnpm dev 

### ISSUE THREAD

**Issue by MarcoPeretti** [heyform/heyform#108]
Hello there,

I cloned the repo and followed the [instructions](https://docs.heyform.net/local-development) to set up the environment on my macOs M1

When I run pnpm dev, I am shown the following error:

[plugin:vite:esbuild] Transform failed with 1 error:
/Users/marco/dev/surveys/heyform/packages/webapp/src/locales/pl.ts:493:2: ERROR: Expected "}" but found "passwordProtection"
/Users/marco/dev/surveys/heyform/packages/webapp/src/locales/pl.ts:493:2
Expected "}" but found "passwordProtection"
491|      translationsDescription:
492|        'Automatycznie przetłumacz pytania formularza na wybrane języki używając <a>OpenAI ChatGPT</a>.'
493|  		passwordProtection: 'Ochrona hasłem',
   |    ^
494|  		passwordProtectionText: 'Zabezpiecz swój formularz prostym do zapamiętania hasłem.',
495|  		passwordProtectionPlaceholder: 'Ustaw hasło do tej strony',
    at failureErrorWithLog (/Users/marco/dev/surveys/heyform/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/marco/dev/surveys/heyform/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:847:29
    at responseCallbacks.<computed> (/Users/marco/dev/surveys/heyform/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/marco/dev/surveys/heyform/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/marco/dev/surveys/heyform/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

![image](https://github.com/heyform/heyform/assets/128880/69066e79-a2ba-4fde-be7d-960d0e248910)

Pressing Esc, shows a spinning wheel but not much else.

**Comment by anarion80** [comment]
Oops, seems to be the problem with my translation PR. I will submit a fix in a moment
